version: '3'
services:
  web:
    build:
      context: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/
    depends_on:
      - db
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/mysql/
  adminer:
    image: adminer:latest
    ports:
      - "8081:8080"
volumes:
  db:
